# Generated by Django 3.1.1 on 2020-10-01 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flights',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.TextField()),
                ('lowest_price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('distance', models.DecimalField(decimal_places=3, max_digits=9)),
                ('aircraft_model', models.CharField(max_length=100)),
                ('aircraft_manufacturer', models.CharField(max_length=100)),
                ('price_per_km', models.DecimalField(decimal_places=2, max_digits=9)),
                ('departure_iata', models.CharField(max_length=3)),
                ('arrival_iata', models.CharField(max_length=3)),
                ('average_speed', models.FloatField()),
                ('flight_duration', models.IntegerField()),
            ],
        ),
    ]
